version: '3.8'

services:
  web:
    build: .
    command: gunicorn news_api.wsgi:application --bind 0.0.0.0:8080 --workers 4
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - 'POSTGRES_HOST_AUTH_METHOD=trust'